Update dependencies and commit lockfile
rust-av/avp pull request #23
Opened 2021-03-11 15:45 UTC by fkaa

Should fix #22

2021-03-11 20:43 UTC, lu-zero requested changes
The lockfile should never be part of the master branch since it causes lots of churn. It can be committed on a release branch once we have one though.

2021-03-11 22:09 UTC, lu-zero approved these changes

2021-03-11 22:09 UTC, merged

2021-03-12 11:25 UTC, kpcyrd commented
Please reconsider this, the lock file is needed for reproducible builds and the build recently broke because cargo wasn't able to find a working combination of dependencies anymore since no working lock file was commited. It also makes it harder to reason about security because it makes knowing the version/git commit the binary was built from insufficient to know if the binary does or doesn't use a vulnerable dependency.

2021-03-12 12:35 UTC, lu-zero commented
I'm happy to add it on releases or let other people manage the releases and updating the Cargo.lock accordingly. I'm against having in in the master branch since it cause lots of spurious commits.

Distributions tend to hate having lockfiles in the way since they prefer to select themselves the dependencies, so the need for it is quite varying depending on who you ask.